### ISSUE TITLE
Questions - Run locally

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [funbiscuit/idea-formatter-plugin#1]
Hi there,

absolute love your project, since it helps me with a good start for my project.
I wanted to know how to run/test it?

I was able to run your docker-image and wanted to test a bit for my project. But i dont want to build a docker image every time i change something, so my question is, what do i need to do?

Also does it requires to have the Ultimate Version?

**Comment by NilsBaumgartner1994** [comment]
Would love if you may get into contact with me for my PhD work: nilsbaumgartner1994@gmail.com

**Comment by funbiscuit** [comment]
Hi!

Plugin can be used with normal Community version of Intellij IDEA, no need for Ultimate. To run locally you will need to first package it into zip by running

```shell
./gradlew buildPlugin
```

Then unzip `formatter-plugin-1.0-SNAPSHOT.zip` from `build/distributions/` to `plugins` directory of your IDEA. Then close IDEA and after that you can run plugin from cli:

```
./idea.sh formatter <args>
```

For example:

```
./idea.sh formatter --style CodeStyle.xml --dry --recursive src
```
